version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5002:5002"
    env_file:
      - backend/.env
    depends_on:
      - cms
    networks:
      - app-network

  cms:
    build:
      context: .
      dockerfile: cms/Dockerfile
    ports:
      - "1337:1337"
    env_file:
      - cms/.env
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
